### ISSUE TITLE
在同时发送文件的时候会异常,应该是那个状态当前为LISTENING  也就是说不支持多线程 是嘛？

### ISSUE THREAD

**Issue by zjianflys** [togettoyou/android-bluetoothChat#1]
`2020-03-17 10:35:59.095 13073-13073/com.zjh.btim D/BluetoothSocket: close() this: android.bluetooth.BluetoothSocket@8993d5f, channel: 6, mSocketIS: android.net.LocalSocketImpl$SocketInputStream@6c43ac, mSocketOS: android.net.LocalSocketImpl$SocketOutputStream@dbf6875mSocket: android.net.LocalSocket@bd1500a impl:android.net.LocalSocketImpl@3e507b fd:java.io.FileDescriptor@12fee98, mSocketState: LISTENING
2020-03-17 10:35:59.096 13073-14078/com.zjh.btim W/System.err: java.io.IOException: read failed, socket might closed or timeout, read ret: -1
2020-03-17 10:35:59.096 13073-13073/com.zjh.btim D/ActivityThread: Remove activity client record, r= ActivityRecord{e7ecad1 token=android.os.BinderProxy@7a38b6f {com.zjh.btim/com.zjh.btim.Activity.ChatActivity}} token= android.os.BinderProxy@7a38b6f
2020-03-17 10:35:59.096 13073-14078/com.zjh.btim W/System.err:     at android.bluetooth.BluetoothSocket.readAll(BluetoothSocket.java:796)
2020-03-17 10:35:59.096 13073-14078/com.zjh.btim W/System.err:     at android.bluetooth.BluetoothSocket.waitSocketSignal(BluetoothSocket.java:749)
2020-03-17 10:35:59.096 13073-14078/com.zjh.btim W/System.err:     at android.bluetooth.BluetoothSocket.accept(BluetoothSocket.java:519)
2020-03-17 10:35:59.096 13073-14078/com.zjh.btim W/System.err:     at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:162)
2020-03-17 10:35:59.096 13073-14078/com.zjh.btim W/System.err:     at android.bluetooth.BluetoothServerSocket.accept(BluetoothServerSocket.java:148)
2020-03-17 10:35:59.096 13073-14078/com.zjh.btim W/System.err:     at com.zjh.btim.Service.BluetoothChatService$AcceptThread.run(BluetoothChatService.java:189)`

**Comment by togettoyou** [comment]
能不能描述一下异常的复现步骤，同时发送是指双发同时向对方发送文件吗？还是指一方同时向对方发送多个文件，不过这种情况的话，我是有显示发送对话框的，也没办法发送多文件测试？不知你是哪种方式？

**Comment by zjianflys** [comment]
就是两边同时发送文件...  调取文件在确认那个弹窗处,同时点,就会抛出这个异常

**Comment by zjianflys** [comment]
或者说  写个循环发字符串,然后同时发送文件,也会抛这个异常

**Comment by togettoyou** [comment]
我在我的两部小米手机测试，两边同时发送文件，是没有问题的，即使一边已先完成接受，另一边还在传输的状态的时候，发送消息也是可以的。多线程的问题[参考代码](https://github.com/togettoyou/android-bluetoothChat/blob/8b14613a9acf63fef2b4b0aae98a2a119681645c/app/src/main/java/com/zjh/btim/Service/BluetoothChatService.java#L300)
发送消息、文件是去开启线程执行的。
另外我修复了选择文件，如选择下载内容中的文件会引发奔溃的问题。
你再重新下载我打包好的apk安装看看问题是否还存在。

**Comment by togettoyou** [comment]
这个抛出的异常并不会影响发送消息或者文件的，你重新下载我修复了的版本看看吧，发生文件尽量选小一点的文件测试，蓝牙传输挺慢的。
